// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class AutoDealership
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? CityId { get; set; }

    public string Street { get; set; }

    public string Number { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<DealershipCar> DealershipCars { get; set; } = new List<DealershipCar>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}