// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class Car
{
    public int Id { get; set; }

    public int CarTypeId { get; set; }

    public int Doors { get; set; }

    public int Seats { get; set; }

    public int Year { get; set; }

    public decimal Price { get; set; }

    public int ColorId { get; set; }

    public int BodyTypeId { get; set; }

    public int EngineId { get; set; }

    public int? BrandId { get; set; }

    public string Model { get; set; }

    public string Generation { get; set; }

    public int? Weight { get; set; }

    public int? MaxSpeed { get; set; }

    public int? GearsCount { get; set; }

    public double? Height { get; set; }

    public double? Width { get; set; }

    public double? Length { get; set; }

    public int? GearBoxId { get; set; }

    public int? FuelTankCapacity { get; set; }

    public int? WheelsCount { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual CarBodyType BodyType { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<CarComfortOption> CarComfortOptions { get; set; } = new List<CarComfortOption>();

    public virtual ICollection<CarMultimediaOption> CarMultimediaOptions { get; set; } = new List<CarMultimediaOption>();

    public virtual ICollection<CarSafetyOption> CarSafetyOptions { get; set; } = new List<CarSafetyOption>();

    public virtual Color Color { get; set; }

    public virtual Engine Engine { get; set; }

    public virtual GearBoxType GearBox { get; set; }
}