// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class CarDelivery
{
    public int Id { get; set; }

    public int SaleId { get; set; }

    public int DistributorId { get; set; }

    public DateOnly DeliveryDate { get; set; }

    public decimal DeliveryCost { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual Distributor Distributor { get; set; }

    public virtual CarSale Sale { get; set; }
}