// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class CarSale
{
    public int Id { get; set; }

    public int DealershipCarId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly SaleDate { get; set; }

    public int? StatusId { get; set; }

    public DateOnly? ExpectedDeliveryDate { get; set; }

    public int? EmployeeId { get; set; }

    public int? PaymentMethodId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<CarDelivery> CarDeliveries { get; set; } = new List<CarDelivery>();

    public virtual Customer Customer { get; set; }

    public virtual DealershipCar DealershipCar { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual SaleStatus Status { get; set; }
}