// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class ComfortOption
{
    public int Id { get; set; }

    public string OptionName { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<CarComfortOption> CarComfortOptions { get; set; } = new List<CarComfortOption>();
}