// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class DealershipCar
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public int? DealershipId { get; set; }

    public int? CarsCount { get; set; }

    public int? CarStatusId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<CarSale> CarSales { get; set; } = new List<CarSale>();

    public virtual DealershipCarStatus CarStatus { get; set; }

    public virtual AutoDealership Dealership { get; set; }

    public virtual ICollection<Lease> Leases { get; set; } = new List<Lease>();
}