// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class Distributor
{
    public int Id { get; set; }

    public string DistributorName { get; set; }

    public string DistributorAddress { get; set; }

    public string DistributorIdentifier { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<CarDelivery> CarDeliveries { get; set; } = new List<CarDelivery>();
}