// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int DealershipId { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<CarSale> CarSales { get; set; } = new List<CarSale>();

    public virtual AutoDealership Dealership { get; set; }

    public virtual ICollection<Lease> Leases { get; set; } = new List<Lease>();
}