// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class LeaseProposal
{
    public int Id { get; set; }

    public int LeaseTypeId { get; set; }

    public bool InsuranceRequired { get; set; }

    public decimal MonthlyPayment { get; set; }

    public string Description { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<LeaseProposalCondition> LeaseProposalConditions { get; set; } = new List<LeaseProposalCondition>();

    public virtual LeaseType LeaseType { get; set; }

    public virtual ICollection<Lease> Leases { get; set; } = new List<Lease>();
}