// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTP_Seed.Models;

public partial class Lease
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public int? ProposalId { get; set; }

    public int CustomerId { get; set; }

    public int DealershipCarId { get; set; }

    public DateOnly LeaseSignDate { get; set; }

    public DateOnly LeaseStartDate { get; set; }

    public DateOnly LeaseEndDate { get; set; }

    public string LeaseUniqueNumber { get; set; }

    public decimal? TotalPrice { get; set; }

    public string Description { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealershipCar DealershipCar { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual LeaseProposal Proposal { get; set; }
}