TRUNCATE TABLE [AutoDealershipStaging].[dbo].[AutoDealerships]
TRUNCATE TABLE [AutoDealershipStaging].[dbo].[Brands]
TRUNCATE TABLE [AutoDealershipStaging].[dbo].[Cars]
TRUNCATE TABLE [AutoDealershipStaging].[dbo].[CarSales]
TRUNCATE TABLE [AutoDealershipStaging].[dbo].[DealershipCars]
TRUNCATE TABLE [AutoDealershipStaging].[dbo].[Leases]



INSERT INTO [AutoDealershipStaging].[dbo].[AutoDealerships]
SELECT * FROM [AutoDealership].[dbo].[AutoDealerships]

INSERT INTO [AutoDealershipStaging].[dbo].[Brands]
SELECT * FROM [AutoDealership].[dbo].[Brands]

INSERT INTO [AutoDealershipStaging].[dbo].[DealershipCars]
SELECT * FROM [AutoDealership].[dbo].[DealershipCars]

SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[Cars] ON
INSERT INTO [AutoDealershipStaging].[dbo].[Cars]
([Id]
      ,[CarTypeId]
      ,[Doors]
      ,[Seats]
      ,[Year]
      ,[Price]
      ,[ColorId]
      ,[BodyTypeId]
      ,[EngineId]
      ,[BrandId]
      ,[Model]
      ,[Generation]
      ,[Weight]
      ,[MaxSpeed]
      ,[GearsCount]
      ,[Height]
      ,[Width]
      ,[Length]
      ,[GearBoxId]
      ,[FuelTankCapacity]
      ,[WheelsCount]
      ,[CreateDate]
      ,[UpdateDate])
SELECT[Id]
      ,[CarTypeId]
      ,[Doors]
      ,[Seats]
      ,[Year]
      ,[Price]
      ,[ColorId]
      ,[BodyTypeId]
      ,[EngineId]
      ,[BrandId]
      ,[Model]
      ,[Generation]
      ,[Weight]
      ,[MaxSpeed]
      ,[GearsCount]
      ,[Height]
      ,[Width]
      ,[Length]
      ,[GearBoxId]
      ,[FuelTankCapacity]
      ,[WheelsCount]
      ,[CreateDate]
      ,[UpdateDate] FROM [AutoDealership].[dbo].[Cars]
SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[Cars] OFF

SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[CarSales] ON
INSERT INTO [AutoDealershipStaging].[dbo].[CarSales]
([Id]
      ,[DealershipCarId]
      ,[CustomerId]
      ,[SaleDate]
      ,[StatusId]
      ,[ExpectedDeliveryDate]
      ,[EmployeeId]
      ,[PaymentMethodId]
      ,[CreateDate]
      ,[UpdateDate])
SELECT [Id]
      ,[DealershipCarId]
      ,[CustomerId]
      ,[SaleDate]
      ,[StatusId]
      ,[ExpectedDeliveryDate]
      ,[EmployeeId]
      ,[PaymentMethodId]
      ,[CreateDate]
      ,[UpdateDate] FROM [AutoDealership].[dbo].[CarSales]
SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[CarSales] OFF

SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[Leases] ON
INSERT INTO [AutoDealershipStaging].[dbo].[Leases]
([Id]
      ,[EmployeeId]
      ,[ProposalId]
      ,[CustomerId]
      ,[DealershipCarId]
      ,[LeaseSignDate]
      ,[LeaseStartDate]
      ,[LeaseEndDate]
      ,[LeaseUniqueNumber]
      ,[TotalPrice]
      ,[Description]
      ,[CreateDate]
      ,[UpdateDate])
SELECT [Id]
      ,[EmployeeId]
      ,[ProposalId]
      ,[CustomerId]
      ,[DealershipCarId]
      ,[LeaseSignDate]
      ,[LeaseStartDate]
      ,[LeaseEndDate]
      ,[LeaseUniqueNumber]
      ,[TotalPrice]
      ,[Description]
      ,[CreateDate]
      ,[UpdateDate] FROM [AutoDealership].[dbo].[Leases]
SET IDENTITY_INSERT [AutoDealershipStaging].[dbo].[Leases] OFF