USE [master]
GO
/****** Object:  Database [AutoDealershipOLAP]    Script Date: 4/19/2024 1:56:10 PM ******/
CREATE DATABASE [AutoDealershipOLAP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoDealershipOLAP', FILENAME = N'C:\Users\Work\AutoDealershipOLAP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoDealershipOLAP_log', FILENAME = N'C:\Users\Work\AutoDealershipOLAP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AutoDealershipOLAP] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoDealershipOLAP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AutoDealershipOLAP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ARITHABORT OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AutoDealershipOLAP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AutoDealershipOLAP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AutoDealershipOLAP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AutoDealershipOLAP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AutoDealershipOLAP] SET  MULTI_USER 
GO
ALTER DATABASE [AutoDealershipOLAP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AutoDealershipOLAP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AutoDealershipOLAP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AutoDealershipOLAP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AutoDealershipOLAP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AutoDealershipOLAP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AutoDealershipOLAP] SET QUERY_STORE = ON
GO
ALTER DATABASE [AutoDealershipOLAP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AutoDealershipOLAP]
GO
/****** Object:  Table [dbo].[Brands]    Script Date: 4/19/2024 1:56:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Brands](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](100) NULL,
 CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cars]    Script Date: 4/19/2024 1:56:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cars](
	[Id] [int] NOT NULL,
	[Model] [nvarchar](100) NULL,
	[BrandId] [int] NULL,
	[Generation] [nvarchar](100) NULL,
 CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarSales]    Script Date: 4/19/2024 1:56:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarSales](
	[Id] [int] NOT NULL,
	[AutoDealershipId] [int] NULL,
	[BrandId] [int] NULL,
	[TotalIncomeLastMonth] [decimal](10, 2) NULL,
	[StartDateId] [int] NULL,
	[EndDateId] [int] NULL,
	[TotalIncomeForCurrentMonth] [decimal](10, 2) NULL,
	[MonthTotalIncomeModifyPercent] [int] NULL,
	[SalesCountForLastMonth] [int] NULL,
	[SalesCountForCurrentMonth] [int] NULL,
	[SalesCountChangeForMonth] [int] NULL,
 CONSTRAINT [PK_CarSales] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dates]    Script Date: 4/19/2024 1:56:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dates](
	[Id] [int] NOT NULL,
	[Year] [int] NULL,
	[Month] [int] NULL,
	[Day] [int] NULL,
 CONSTRAINT [PK_Dates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Leases]    Script Date: 4/19/2024 1:56:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Leases](
	[Id] [int] NOT NULL,
	[CarId] [int] NULL,
	[Price] [decimal](10, 2) NULL,
	[PreviousLeaseModifyPercent] [int] NULL,
	[LeaseSignDateId] [int] NULL,
	[LeaseStartDateId] [int] NULL,
	[LeaseEndDateId] [int] NULL,
	[LastLeaseId] [int] NULL,
 CONSTRAINT [PK_Leases] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Brands]  WITH CHECK ADD  CONSTRAINT [FK_Brands_CarSales] FOREIGN KEY([Id])
REFERENCES [dbo].[CarSales] ([Id])
GO
ALTER TABLE [dbo].[Brands] CHECK CONSTRAINT [FK_Brands_CarSales]
GO
ALTER TABLE [dbo].[CarSales]  WITH CHECK ADD  CONSTRAINT [FK_CarSales_Dates] FOREIGN KEY([StartDateId])
REFERENCES [dbo].[Dates] ([Id])
GO
ALTER TABLE [dbo].[CarSales] CHECK CONSTRAINT [FK_CarSales_Dates]
GO
ALTER TABLE [dbo].[CarSales]  WITH CHECK ADD  CONSTRAINT [FK_CarSales_Dates1] FOREIGN KEY([EndDateId])
REFERENCES [dbo].[Dates] ([Id])
GO
ALTER TABLE [dbo].[CarSales] CHECK CONSTRAINT [FK_CarSales_Dates1]
GO
ALTER TABLE [dbo].[Leases]  WITH CHECK ADD  CONSTRAINT [FK_Leases_Cars] FOREIGN KEY([CarId])
REFERENCES [dbo].[Cars] ([Id])
GO
ALTER TABLE [dbo].[Leases] CHECK CONSTRAINT [FK_Leases_Cars]
GO
ALTER TABLE [dbo].[Leases]  WITH CHECK ADD  CONSTRAINT [FK_Leases_Dates] FOREIGN KEY([LeaseSignDateId])
REFERENCES [dbo].[Dates] ([Id])
GO
ALTER TABLE [dbo].[Leases] CHECK CONSTRAINT [FK_Leases_Dates]
GO
USE [master]
GO
ALTER DATABASE [AutoDealershipOLAP] SET  READ_WRITE 
GO
